version: '{build}'

environment:
  ARCH: 32

build_script:
- cmd: |
    nuget install zlib.v140.windesktop.msvcstl.dyn.rt-dyn

    cmake --version

    mkdir build

    cd build

    cmake -DBUILD_SAMPLE=ON -DBUILD_TESTS=ON -G"Visual Studio 14 2015" -DZLIB_INCLUDE_DIR:PATH=C:\projects\libsquash\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\include -DZLIB_LIBRARY_RELEASE:FILEPATH=C:\projects\libsquash\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\lib\native\v140\windesktop\msvcstl\dyn\rt-dyn\Win32\RelWithDebInfo\zlib.lib ..

    cmake --build . --config Release

    copy C:\projects\libsquash\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\lib\native\v140\windesktop\msvcstl\dyn\rt-dyn\Win32\RelWithDebInfo\zlib.dll Release

    ctest --verbose
