version: '{build}'

environment:
  matrix:
  - GENERATOR: "Visual Studio 14 2015"
    ARCH: 32
  - GENERATOR: "Visual Studio 14 2015 Win64"
    ARCH: 64
  - GENERATOR: "Visual Studio 12 2013"
    ARCH: 32
  - GENERATOR: "Visual Studio 12 2013 Win64"
    ARCH: 64

build_script:
- ps: |
    nuget install zlib
    
    tree /F

    cmake --version

    mkdir build

    cd build

    cmake -G"$env:GENERATOR" -DZLIB_INCLUDE_DIR:PATH=zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\include -DZLIB_LIBRARY_RELEASE:FILEPATH=zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\lib\native\v140\windesktop\msvcstl\dyn\rt-dyn\Win32\RelWithDebInfo\zlib.lib ..

    cmake --build .

    ctest
