version: '{build}'

environment:
  matrix:
  - GENERATOR: "Visual Studio 14 2015"
    ARCH: 32
  - GENERATOR: "Visual Studio 14 2015 Win64"
    ARCH: 64
  - GENERATOR: "Visual Studio 12 2013"
    ARCH: 32
  - GENERATOR: "Visual Studio 12 2013 Win64"
    ARCH: 64

build_script:
- ps: |
    Install-Package zlib

    cmake --version

    mkdir build

    cd build

    cmake -G"$env:GENERATOR" ..

    cmake --build .

    ctest
